version: '3.0'

services:

  mariadb:
    image: mariadb:5.5

    environment:
      # - MYSQL_DATABASE=informatics
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=123456

    volumes:
      - ./create-databases.sql:/docker-entrypoint-initdb.d/setup.sql

  mongo:
    # No way of using official image :-(
    image: aashreys/mongo-auth:latest

    environment:
      - AUTH=no
      - MONGODB_ADMIN_USER=root
      - MONGODB_ADMIN_PASS=123456
      - MONGODB_APPLICATION_DATABASE=test
      - MONGODB_APPLICATION_USER=testuser
      - MONGODB_APPLICATION_PASS=123456

  redis:
    image: redis

  informatics:
    build:
      context: ../rmatics

    depends_on:
      - mariadb
      - redis
      - mongo

    environment:
      - FLASK_ENV=testing
      - MONGO_URI='mongodb://testuser:123456@mongo/test'
      - URL_ENCODER_ALPHABET='sdgdfgbfhghg'
      - SQLALCHEMY_DATABASE_URI='mysql+pymysql://root:123456@mariadb/informatics'
      - SQLALCHEMY_TRACK_MODIFICATIONS = False
      - SECRET_KEY='dkjbnfjnvfvkmflvmflmv'
      - EJUDGE_NEW_CLIENT_URL='dcdc'
      - REDIS_URL='redis://redis:6379/0'

    command: 'bash -c "sleep 10 && flask test --teamcity"'
